<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\..\assets\branding\h2-notes-app-icon-v1.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\..\assets\branding\h2-notes-app-icon-v1.png" Link="Assets\Branding\h2-notes-app-icon-v1.png" />
    <Content Include="..\..\assets\branding\h2-notes-app-icon-v1.ico" Link="Assets\Branding\h2-notes-app-icon-v1.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
